[project]
name = "ctms-app"

[[services]]
name = "ctms-backend"
source = "."
builder = "DOCKERFILE"

[services.variables]
JAVA_OPTS = "-Xmx512m"
PORT = "8080"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
