services:
  # Spring Boot Backend Service
  - type: web
    name: ctms-backend
    env: docker
    plan: free
    envVars:
      - key: DB_URL
        value: postgresql://postgres:VMFAbjsutWsrDySptrMsvlTbmZAErkGE@postgres.railway.internal:5432/railway
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: VMFAbjsutWsrDySptrMsvlTbmZAErkGE
      - key: JAVA_OPTS
        value: "-Xmx512m"
    healthCheckPath: /api/clients
    autoDeploy: true
